name: Actions on any pull request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Run tests & check jar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build
#        continue-on-error: true
        run: gradle build

#      - name: Publish Test Report
#        uses: scacap/action-surefire-report@v1
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          report_paths: '**/build/test-results/test/TEST-*.xml'

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Unit Test Results
          files: test-results/**/*.xml
          report_individual_runs: true
          deduplicate_classes_by_file_name: false

      - name: Upload test report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test report
          path: build/reports/tests/test/

#      - name: Test
#        run: gradle test

      - name: Build ShadowJar
        run: gradle shadowJar
