# This is a basic workflow to help you get started with Actions

name: Run test on pull request

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run_tests:
    # The type of runner that the job will run on (windows-latest, macos-latest)
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1

      - name: Build
        run: gradle build

      - name: Test
        run: gradle test

      - name: ShadowJar
        run: gradle shadowJar
