name: Actions on any pull request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Run tests & check jar
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build
        continue-on-error: true
        run: gradle build

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: Test report
          path: build/reports/tests/test/

      - name: Test
        run: gradle test

      - name: Build ShadowJar
        run: gradle shadowJar
